name: Label Stalled PRs
on:
  schedule:
    - cron: '15 15 * * *' # Run every day at 15:15 UTC / 7:15 PST / 8:15 PDT
jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Stale PRs
    steps:
    - uses: aws-actions/stale-issue-cleanup@v3
      with:
	stale-pr-message: This PR has been open without activity for more than 30 days. Labeling this issue stalled. Please close the PR if it is no longer necessary.
	stale-issue-label: stalled
        exempt-issue-labels: awaiting-approval
        stale-pr-label: no-pr-activity
        exempt-pr-labels: awaiting-approval
        response-requested-label: response-requested

	closed-for-staleness-label: closed-for-staleness
	  
        stale-pr-label: 'stalled'
        stale-pr-message: 'This PR is stalled because it has been open for 30 days with no activity.'
        days-before-stale: 30
        repo-token: ${{ secrets.GITHUB_TOKEN }}